"""
Sample data
MIRVAGEYSEASSRVNCGRLAYSCTDSYPFVREVHHMCSKERVAPNHMFVTVYCLQVHCMIDPISECLMFRCYDDSLTEFNCLNLFPRVFADFYQLVLSYDGMEVSSGYPLDQPSKQQPPKHDYNDGDMILIVLPIKGDRKNYLGALPRRGRRQRKAIRSNNHSCVGFSKIYHKGNTKTQECALPRVWYGKIYTTVLASHMGLDMDPYNNETWHKCYPYLCHSDYASMFVQEKMMRTMHWMCIHYDDCQLTRHLSGTLWKHPYMASGACAQEVYHNFICEPNHRRFDTSNKTVSHCRNIRKHGLHIGMIMVVMADIKEGCWLICIHIQQAAYMPEEGEDGYVDITNVANWEDALKYQQCTGFMPPYHYGHPYIFCDERCNTFFWLTYMELFMKHYGSDLLPMNQRQMNSYWMAQLRKHWVAVIHSDCSRFAMGEDYEAHWKPETASNVGDHSWGNVTADTTVWSYIYYRPVRQPGFHQQSELNDWRYMARQYWPCVRVQEYGWTFPTTQNWQDGHEPKWSFAKIWVNTQCGDTHGHAHLMIFPFWVTNLDVVWPHCYWLAYPPPKHHKVLQAYQMWGGCDQTYVPWVMGCRGDKWCGNFKKTFWMPGECQNDWMHNCNSMHNYRKVSMTIFMLTATWQAPKFQMMMSWHFIYQCHWAYNHMTILVVRPARCKGLWEYMIKRNVQMIIAWSDYPSNVGFPPEDLYGRDCEALLCMIAIHHCPMSQWGRAAVAANFQLSSPFVCAWVHLMWFIQDNVDIHAKEKMYKFPREYEEMQTGMRCKPLEAFWYKIVCHKSSAQGIYEHDTGPIWGQASNLWIIKRTDAGGGPVWMVVGENGEKEERYWLFKVRQQVDIQGFLQKQADRMFHADITCEKAAPTIAPYFMLNKAVYKSMQELSSLCSGKGLLFMERLIVQRYDWITFQDDSTEITCCNRWQDLTRAWNNRWQWILEEILPSNFYVIAEIASSCITTAKEWHHSCLTFFTPKNNHHTNGWGYPMMSMVL

Result
78976
"""


import sys
from collections import defaultdict

t = """
UUU F      CUU L      AUU I      GUU V
UUC F      CUC L      AUC I      GUC V
UUA L      CUA L      AUA I      GUA V
UUG L      CUG L      AUG M      GUG V
UCU S      CCU P      ACU T      GCU A
UCC S      CCC P      ACC T      GCC A
UCA S      CCA P      ACA T      GCA A
UCG S      CCG P      ACG T      GCG A
UAU Y      CAU H      AAU N      GAU D
UAC Y      CAC H      AAC N      GAC D
UAA Stop   CAA Q      AAA K      GAA E
UAG Stop   CAG Q      AAG K      GAG E
UGU C      CGU R      AGU S      GGU G
UGC C      CGC R      AGC S      GGC G
UGA Stop   CGA R      AGA R      GGA G
UGG W      CGG R      AGG R      GGG G
""".split()
codon_table = dict(zip(t[0::2], t[1::2]))

amino_frequency_table = defaultdict(int)
for k, v in codon_table.items():
    amino_frequency_table[v] += 1


def compute_combos(protein_string):
    combos = 1

    for _ in protein_string:
        combos = (combos * amino_frequency_table[_]) % 1000000

    # Account for Stop Codons
    return (combos * 3) % 1000000


if __name__ == '__main__':
    protein_string = open(sys.argv[1]).read().rstrip()
    print(compute_combos(protein_string))
